# Site settings
title: Upendra Pratap Kushwaha
default_author: Upendra Pratap Kushwaha
description: "Online Territory of Upendra Pratap Kushwaha"  # used in site head

# register on google analytics and replace this token
google_analytics: UA-76016934-2
# disque comments are broken if you send http:// along with url, this url is same as the one given on disqus
# Deleting the value would remove it from footer.
disqus_url: upendra.tech
disqus_id: upendra-tech
# register on feedburner and replace this url. Deleting the value will remove it from footer.
feedburner_url: https://feedburner.google.com/fb/a/mailverify?uri=UpendraPratapKushwaha&amp;loc=en_US

# skype Chat
skypeid: upi653 # if want to remove skype chat , remove this setting


# footer details. Deleting the value would remove it from footer.
github_username:  upendra243
facebook_username:  upendra243
email: root@upendra.tech
stackoverflow_username: 3340491/upendra243
twitter_username : upi653
linkedin_username : upendra243
keybase_username : upendra243
copyright_name: Upendra Pratap Kushwaha
rss : true

# used for portfolio on home page
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: blog/page:num

# gem dependencies
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]
